### ISSUE TITLE
Not compatible with Thunberd 68.11

### ISSUE THREAD

**Issue by cmtheo** [spymastermatt/thunderbird-monterail#119]
All Monterail themes currently don't function with Thunderbird 68.xx.  Is there a work around or do we have to wait for an update to the theme?

**Comment by ghost** [comment]
I thought it was only me. I installed thunderbird 68.11 but the theme doesn't seem to load at all.

**Comment by NicoPL** [comment]
Same for me.
Actually, non of the themes listed in the official https://addons.thunderbird.net seem compatible with 68.xx

**Comment by advancingu** [comment]
This repository is clearly not maintained anymore. For me, the base theme itself is still working fine with TB68.1.

In https://github.com/spymastermatt/thunderbird-monterail/pull/120 I published a fix for the folder pane background color so that others can apply it manually to their copies.

**Comment by nickvergessen** [comment]
For me since the last update to 68.1.2 emails are not colored in the list anymore if they are tagged. this basically makes it unusable for me :crying_cat_face:

**Comment by nickvergessen** [comment]
@AlexandreRio I fixed it with https://github.com/spymastermatt/thunderbird-monterail/pull/121
But now all unread emails are marked blue. Not sure this is better for everyone, but as long as you have no blue tag, it does it's job I'd say

**Comment by Dahaniel** [comment]
> @AlexandreRio I fixed it with #121
> But now all unread emails are marked blue. Not sure this is better for everyone, but as long as you have no blue tag, it does it's job I'd say

For me everything looks fine, no blue mails. Thanks for the fix!

**Comment by AlexandreRio** [comment]
@nickvergessen Just tested your fix, everything looks good to me, thanks!

**Comment by frederik-elwert** [comment]
@advancingu Thanks for the patch. Unfortunately, it does not seem to work for me (on Ubuntu, using the system theme). I still have a light background with a light-ish font, making it hardly legible. Any idea what might be causing this? (It does work, however, with the dark theme.)

**Comment by advancingu** [comment]
@frederik-elwert Try again with the new change to my PR #120 .

**Comment by frederik-elwert** [comment]
@advancingu Yes, that one works perfectly, thanks!

**Comment by qazip** [comment]
Holly hell, this is so confusing... This repo is obviously dead and the original owner has been MIA for 3 years now. It would be nice if someone set a new repo... @advancingu, can't you set a new repo (with issues enabled and all that) for this awesome theme?

**Comment by conema** [comment]
Hi guys, I don't know if all of you know that I'm maintaining from one year the [dark ](https://github.com/conema/monterail-dark) and [fulldark ](https://github.com/conema/monterail-fulldark) version of the theme, that is the one that you can find in the official TB addons webpage. It's fully (I hope) compatible with the last version of TB.

**Comment by subhasiscgr** [comment]
Is there any tutorial on how to install themes manually? I am new to Thunderbird and the xpi file is being rejected. Even changing strictcompatibility to false did not help.
